### ISSUE TITLE
minor issue: Invalid git url in README.md

### ISSUE THREAD

**Issue by alexchua0108** [zhanglongqi/xnergy-charger-rcu#1]
@zhanglongqi 

At README.md file-Line 39

instead of
`git clone https://bitbucket.org/zhanglongqi/xnergy-charger-rcu.git catkin_ws/src/xnergy_charger`

it should be
`git clone https://github.com/zhanglongqi/xnergy-charger-rcu.git catkin_ws/src/xnergy_charger`

**Comment by zhanglongqi** [comment]
Thanks. Noted.
